repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: debug-statements
-   repo: git://github.com/pre-commit/mirrors-eslint
    rev: v7.0.0-alpha.0
    hooks:
    -   id: eslint
        types: [file]
        files: \.jsx?$
        exclude: |
            (?x)(
                ^dotenv/|
                ^webpack/
            )
        additional_dependencies:
        - eslint@6.8.0
        - eslint-config-airbnb@18.0.1
        - eslint-plugin-import@2.20.0
        - eslint-plugin-jest@23.6.0
        - eslint-plugin-jsx-a11y@6.2.3
        - eslint-plugin-react@7.18.0
        - eslint-plugin-react-hooks@1.7.0
-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: 'v1.0.0'
    hooks:
    -   id: check-gitlab-ci