repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v6.8.0'
    hooks:
    -   id: eslint
-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: 'v1.0.0'
    hooks:
    -   id: check-gitlab-ci
-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.0
    hooks:
    -   id: dockerfile_lint