apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coco-cms-frontend.fullname" . }}
  labels:
    {{- include "coco-cms-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "coco-cms-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coco-cms-frontend.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
          - name: {{ . }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.app }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
