// Action Types
export const SET_PRODUCT_LIB_DATA = 'SET_PRODUCT_LIB_DATA';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_FOLDERS = 'SET_FOLDERS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const SET_ENABLED = 'SET_ENABLED';
export const ADD_PRODUCTS_TO_FOLDER = 'ADD_PRODUCTS_TO_FOLDER';
export const RESET_DELETE_PRODUCT_ID = 'RESET_DELETE_PRODUCT_ID';
export const DESTROY_PRODUCT_LIB_DATA = 'DESTROY_PRODUCT_LIB_DATA';

// Enums
export const GENERAL_LABEL = 'General Folder';
