export const SET_SCENE_EDITOR_DATA = 'SET_SCENE_EDITOR_DATA';
export const SET_SCENE_HOTSPOTS = 'SET_SCENE_HOTSPOTS';
export const SET_CURRENT_SCENE_ID = 'SET_CURRENT_SCENE_ID';
export const SET_SCENE_DATA = 'SET_SCENE_DATA';
export const DESTROY_SCENE_DATA = 'DESTROY_SCENE_DATA';